### ISSUE TITLE
Adding a method as an extension and the method was deleted.

### ISSUE THREAD

**Issue by unchartedworks** [dionisiydk/Calypso#107]
Calypso Version: Sep 17, 2017
Pharo Version: Pharo 6.1 64-bit
OS: macOS High Sierra
Impact: it's difficult to use Calypso to develop extensions.

<img width="486" alt="screen shot 2017-10-27 at 18 03 32" src="https://user-images.githubusercontent.com/4646838/32113699-50871a28-bb41-11e7-9707-6acfe5380f57.png">

**Comment by dionisiydk** [comment]
How exactly you added method as extension?

**Comment by unchartedworks** [comment]
1. Right click the method.
2. Click tag methods.
3. Enter "extensions".

**Comment by dionisiydk** [comment]
Adding extension using star convention is not supported and will not be supported. The feedback for this will be added, look at #96 .
For your scenario you should choose menu item "move to extension package" instead of "tag methods".
Also you can add method to package directly from method editor where you create or modify methods. Notice checkbox "extension" at status bar of method editor.
