### ISSUE TITLE
Classes shouldn't be abstract just because they don't override an abstract method

### ISSUE THREAD

**Issue by peteruhnak** [dionisiydk/Calypso#158]
Example: `ReAbstractRule` has `basicCheck:` as abstract that you normally override in subclasses, but if you need a bit more complex checking, then instead of basicCheck: you override `check:forCritiquesDo:` (which is the method normally calling basicCheck:). But then the class is still marked as abstract (such as `ReInvocationSequenceRule`), because `basicCheck:` has not been overriden.

**Comment by dionisiydk** [comment]
It is general behaviour of Pharo 7. So it is not the issue of Calypso. I
just keep it same.

#isAbstract was added to the Behavior.  And it checks unimplemented
abstract methods

2018-01-24 11:49 GMT+01:00 Peter Uhnak <notifications@github.com>:

**Comment by dionisiydk** [comment]
So normally in such cases you should implement unused method with
#shouldNotImplement.

Also I think such method is also shown as a critique to the class

2018-01-24 11:57 GMT+01:00 Denis Kudriashov <dionisiydk@gmail.com>:

**Comment by peteruhnak** [comment]
> It is general behaviour of Pharo 7.

But I am on Pharo 6; maybe it was backported?

**Comment by dionisiydk** [comment]
I just copied this approach from pharo 7 to calypso plugin

24 янв. 2018 г. 11:59 пользователь "Peter Uhnak" <notifications@github.com>
написал:

It is general behaviour of Pharo 7.

But I am on Pharo 6; maybe it was backported?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/dionisiydk/Calypso/issues/158#issuecomment-360095415>,
or mute the thread

**Comment by dionisiydk** [comment]
So I close it. If you want different behaviour propose it for Pharo 7. Then I adopt it for Calypso

**Comment by peteruhnak** [comment]
Ok, no worries then. Thanks!
