### ISSUE TITLE
Browsing method from Debugger after changing a block raises an error

### ISSUE THREAD

**Issue by peteruhnak** [dionisiydk/Calypso#184]
Browsing method from Debugger after changing a block raises an error

tested on latest (2/11/18) dev version

how to reproduce:
1. create class `Something` with the following classes

```smalltalk
breakIt
	self installBreakIt.
	self executeBreakIt

executeBreakIt
	block value

installBreakIt
	block := [ self iDontExist ]
```
(basically the block most be created in a different method than where it is executed)

2. call `Something new breakIt`
3. debug, and change inside debugger the `self iDontExist` to something else (e.g. `self yourself`)

![image](https://user-images.githubusercontent.com/1276328/36071670-b239caf2-0f12-11e8-87ef-141030891e73.png)

4. save; question for browsing will appear
![image](https://user-images.githubusercontent.com/1276328/36071661-6f36f52c-0f12-11e8-80d6-7f436cab575e.png)

5. click browse... this error appears

![image](https://user-images.githubusercontent.com/1276328/36071647-f764314a-0f11-11e8-99b3-f53b78402157.png)

**Comment by dionisiydk** [comment]
The code which does not work uses low level Nautilus methods:
```Smalltalk
DebugContext>>blockNotFoundDialog: aMethod with: aText
  "......................"
"let's browse the given method with the edited contents"
	browser := aMethod browse.
	browser 
		contents: aText; 
		changed: #contents.
	browser codeTextMorph 
		hasUnacceptedEdits: true
```
It is horrible. 
Any idea how to fix it?

Generally I do not understand why we forbid method changes in that case. 
Instead of current logic we can just compile new method and ask user to browse it with notification that it can't be installed into the current stack.
I will open issue for this. 
It also could allow new methods creation from the debugger. This restriction is also always surprised me.

**Comment by dionisiydk** [comment]
I added this one https://pharo.fogbugz.com/f/cases/21328/Better-logic-to-edit-methods-in-debugger-which-are-not-in-the-stack

**Comment by dionisiydk** [comment]
And pull request https://github.com/pharo-project/pharo/pull/872.

For Pharo 6 it will stay broken.

**Comment by dionisiydk** [comment]
Now it is integrated in Pharo 7. So I close issue
