### ISSUE TITLE
Comment pane should keep focus when changing classes

### ISSUE THREAD

**Issue by bencoman** [dionisiydk/Calypso#33]
To get a quick overview of a package architecture, I like to flip through all the class comments.  Currently changing class moves the focus away from the Comments tab, so it takes extra clicks to see it.

**Comment by dionisiydk** [comment]
Yes. I also thought about it at some point and forgot :)

**Comment by dionisiydk** [comment]
Ok I found solution according to current tabs management logic. Now most priority tab is activated by default. And to support "desired tab activation" Calypso needs swap priorities between non active and active tabs when new tab is selected. And it should do it only for tabs which belongs to same browser context: if user switches to class tab from method tab then class tab should be not get more priority because instead following switch to another method will not make new method tab active

**Comment by bencoman** [comment]
Will that change the displayed order of the tabs?  That might not be good.

**Comment by dionisiydk** [comment]
No. Tabs has separated priorities for ordering and default selection (#priority and #activationPriority).

**Comment by dionisiydk** [comment]
Done in dev version
